chartVersion: 0.1.0
appVersion: 10.0.2
sources:
- https://www.tenable.com/
- https://hub.docker.com/r/tenableofficial/nessus

values:
  kubeVersionOverride: 1.22.3
  service:
    enabled: true
    port: 8834
    targetPort: 8834
    type: ClusterIP
    udp:
      enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx-internal
    host: nessus.mydomain.com
    tls:
      enabled: true
  image:
    repository: tenableofficial/nessus
  envFrom:
  - secretRef:
    name: '{{ include "nessus.fullname" . }}'
  secrets:
    data:
      USERNAME: admin
      PASSWORD: admin
      ACTIVATION_CODE: 1234-5678-90AB-CDEF-1234 
