# Overrides the chart's name
nameOverride: null

# Overrides the chart's computed fullname
fullnameOverride: null

kubeVersionOverride: 1.22.3

# Number of replicas for the pod
replicas: 1

# The number of old replicaSets to retain to allow rollback
revisionHistoryLimit: 2

# Annotations for the pod
podAnnotations: {}

# The name of the ServiceAccount to use for the pod
serviceAccountName: ""
#serviceAccountName: '{{ include "elasticmq.fullname" . }}'

# Image pull secrets for docker images
imagePullSecrets: []

# Pod anti-affinity
affinity: {}

# Tolerations for the pod
tolerations: []

# Node selector for the pod
nodeSelector: {}

# SecurityContext for the pod
podSecurityContext: {}

image:
  # Docker image registry for the image
  registry: null
  # Docker image repository for the image
  repository: softwaremill/elasticmq
  # Docker image tag for the image
  tag: null
  # Docker image pull policy
  pullPolicy: Always

# Configures the liveness probe for the container
livenessProbe: {}

# Configures the readiness probe for the container
readinessProbe: {}

# Define command for the container
command: []

# Define arguments for the container
args: []

# The SecurityContext for the container
containerSecurityContext: {}

# Environment variables to add to the pod (key: value)
env: {}

# Environment variables from secrets or configmaps to add to the pod
envFrom: []

# Volume mounts to add to the the pod
volumeMounts: 
- mountPath: /opt
  name: '{{ include "elasticmq.fullname" . }}-config'

# Resource requests and limits for the pod
resources: {}

# Volumes to add to the pod
volumes: 
- configMap:
    name: '{{ include "elasticmq.fullname" . }}-config'
  name: '{{ include "elasticmq.fullname" . }}-config'

config: |
  elasticmq.conf: ''

secrets: {}


service: 
  tcp:
    enabled: true
    services:
    - port: 9324
      portName: svc
      targetPort: 9324
      type: ClusterIP
    - port: 9325
      portName: ui
      targetPort: 9325
      type: ClusterIP
  udp:
    enabled: false

ingress: 
  annotations:
    kubernetes.io/tls-acme: 'true'
  enabled: true
  host: elasticmq.mydomain.com
  ingressClassName: nginx-internal
  service:
    port: 9325
  tls:
    enabled: true

ingressList: []
