{{- if .Values.service.tcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.tcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "elasticmq.labels" . | nindent 4 }}
  name: {{ include "elasticmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- range $service := .Values.service.tcp.services }}  
  - name: {{ $service.portName | default "http" }}
    port: {{ $service.port | default "80" }}
    targetPort: {{ $service.targetPort | default $service.port | default "80" }}
    protocol: TCP
    {{- with $service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- end }}  
  selector:
    {{- include "elasticmq.matchLabels" . | nindent 4 }}
  type: {{ .Values.service.tcp.type }}
{{- end }}
