apiVersion: apps/v1
kind: Statefulset
metadata:
  labels:
    {{- include "grafana-agent-eventhandler.labels" . | nindent 4 }}
  name: {{ include "grafana-agent-eventhandler.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "grafana-agent-eventhandler.fullname" . }}
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "grafana-agent-eventhandler.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grafana-agent-eventhandler.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ tpl . $ }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: grafana-agent-eventhandler
        image: {{ include "grafana-agent-eventhandler.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.command }}
        command:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.args }}
        args:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.containerSecurityContext }}
        securityContext: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.env }}
        env:
        {{- range $key, $value := . }}
        - name: {{ $key }}
        {{- if kindIs "map" $value }}
          {{- toYaml $value | nindent 10 }}
        {{- else }}
          value: {{ tpl $value $ | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- with .Values.envFrom }}
        envFrom:
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts: {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes: 
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
  {{- with .Values.volumeClaimTemplates }}    
  volumeClaimTemplates:
  {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
